[[redirects]]
  from = "/host/*"
  to = "/host/index.html"
  status = 200
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200
[[redirects]]
  from = "/"
  to = "/host/"
  status = 302